<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <AssemblyName>DS4BatteryMapper</AssemblyName>
    <RootNamespace>DS4BatteryMapper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HidLibrary" Version="3.3.5" />
  </ItemGroup>

</Project>
